import express from 'express';
import adminAuth from '../middleware/auth.js';
import { bulkquestions, deletequestions, deleteusers, getQuestions, getreport, getstats, getuser, getuserid, postquestions, putquestions, updateuser } from '../controllers/admin.controller.js';
const router = express.Router();
router.use(adminAuth);
router.get('/stats', getQuestions);
router.get('/questions', getstats);
router.post('/questions', postquestions);
router.put('/questions/:id', putquestions);
router.delete('/questions/:id', deletequestions);
router.post('/questions/bulk', bulkquestions);
router.get('/users', getuser);
router.get('/users/:id', getuserid);
router.patch('/users/:id', updateuser);
router.delete('/users/:id', deleteusers);
router.get('/reports', getreport);
export default router;